artifacts_root : artifacts

data_ingestion :
  root_dir : artifacts/data_ingestion
  source_URL : https://github.com/sushant1009/Mlops_dataset_Model/raw/main/data.zip
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion/

data_validation :
  root_dir : artifacts/data_ingestion
  unzip_data_dir : artifacts/data_ingestion/winequality-red.csv
  status_file : artifacts/data_ingestion/status.txt

data_transformation :
  root_dir : artifacts/data_transformation
  data_path : artifacts/data_ingestion/winequality-red.csv


  